baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'JAMSite'
theme = 'tale'

disqusShortname = "jamsite-1"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about/"
    weight = 0
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/posts/"
    weight = 0